version: "2"

services:
  client:
    build: ./client
    ports:
      - 8080:8080
    environment:
      - BACKEND_URL="http://localhost:9000/"
  backend:
    build: ./backend
    ports:
      - 9000:9000
  apache:
    image: 'bitnami/apache:latest'
    ports:
      - '80:8080'
      - '443:8443'
